Feature/notification engine
jakesboy2/MeetingScheduler pull request #58
Opened 2020-04-03 01:13 UTC by mbsim08

from master to dev, sorry!

2020-04-03 01:58 UTC, calebpower requested changes
Okay, so... this is what I would recommend for testing this out.

```bash
git fetch && git checkout feature/notification-engine
git pull
git checkout dev
git pull
git branch merge-dev
git checkout merge-dev
git merge feature/notification-engine
```

The above might be too verbose, but that's a simulation of what happens if I were to merge these. There are a couple of issues that drastically decrease usability. First: the flashy circle thing, it comes up as a DOM element between the cursor and links, so often it requires clicking a link several times before the link actually gets clicked. Also, the login page is completely broken now. I went and tested this on Firefox and on Chrome.

Once those get fixed, we can certainly merge those changes in.

2020-04-03 02:07 UTC, mbsim08 commented
okay, so I got the login page fixed. It's because I forgot to add </div> at the end of cursor class.
For mouse trail... Do you have any recommendations to solve the issue?

2020-04-03 02:08 UTC, mbsim08 commented
I forgot to add </div>*

2020-04-05 21:17 UTC, calebpower approved these changes

2020-04-05 21:17 UTC, merged